### ISSUE TITLE
t/check/rawcommand.t freezes - AnyEvent->condvar->recv blocking

### ISSUE THREAD

**Issue by jbarrett** [xsawyerx/juno#3]
- 5.16.3/i686-linux
- 5.18.0/i686-linux
- 5.18.1/x86_64-linux

The condvar never receives:

``` perl
fork_ok( 2, sub {
    $check->check;
    $cv->recv;
} );
```

Though it does if we add an on_fail callback:

``` perl
my $cv    = AnyEvent->condvar;
my $check = Juno::Check::RawCommand->new(
    hosts     => ['thedude'],
    cmd        => 'pick %h',
    on_success => sub { $cv->send },
    on_fail => sub { $cv->send },
);
```

I have yet to ascertain if this means my environments are broken and the test should fail or if the test is broken. [CPAN Tester results](http://www.cpantesters.org/distro/J/Juno.html) suggest the former, but I cannot ascertain where the breakage is.

**Comment by haarg** [comment]
I believe this is due to changes in System::Command.  The test tries to mock out most of it, but doesn't mock the close method, which ends up throwing, so the success callback is never used and it blocks forever.  If the test were to mock out System::Command::close, the test should work correctly.

**Comment by xsawyerx** [comment]
@haarg how did you get to this now? :)

**Comment by haarg** [comment]
Compatibility testing for Moo changes.  I've been testing all modules downstream of Moo while preparing a new release.  If the tests were failing, I would just note it as not having to do with the changes in this release.  But tests that hang forever are more annoying to deal with.

**Comment by xsawyerx** [comment]
I'll try to deal with this today and release a new version.

**Comment by xsawyerx** [comment]
Fixed and released.
@haarg++
@jbarrett++
